### ISSUE TITLE
Dynamic source configuration does not work

### ISSUE THREAD

**Issue by chendrix** [starkandwayne/bosh2-errand-resource#6]
The documentation shows the availability of using dynamic source configuration, but I think we ran into a problem.

```
resources:
- name: bosh-errand
  type: bosh-errand
  source:
    # Overridden by source_file in the tasks
    deployment: DONOTUSE
    target: DONOTUSE
    client: DONOTUSE
    client_secret: DONOTUSE
```

```
- put: bosh-errand
  params:
    name: errand-name
    source_file: some-path/source_file.json
```

Then on the automatic get that happens after the put, you get

```
Fetching info: Performing request GET 'https://DONOTUSE:25555/info': Performing GET request: Retry: Get https://DONOTUSE:25555/info: dial tcp: lookup DONOTUSE on ... no such host
```

It looks like you need to add params to your `InRequest` to also allow `source_file`, and then it could be configured as such:

```
- put: bosh-errand
  params:
    name: errand-name
    source_file: some-path/source_file.json
  get_params:
    source_file: some-path/source_file.json
```
